### ISSUE TITLE
Validation problem: `parent` isn't set for nested serializer's fields on the validation stage

### ISSUE THREAD

**Issue by ruscoder** [beda-software/drf-writable-nested#1]
I had found a problem on the validation stage when I used `UniqueValidator` for nested serializer's field.
I've found the root of the problem - parent isn't set on the validation stage.

**Comment by cjroth** [comment]
Same as https://github.com/beda-software/drf-writable-nested/issues/28

**Comment by cjroth** [comment]
I believe this fixes it: https://github.com/beda-software/drf-writable-nested/pull/29

**Comment by ruscoder** [comment]
@cjroth #29 is connected to one-to-one relations only. This issue relates to the more common problem and only on the validation stage.

**Comment by ruscoder** [comment]
http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers

**Comment by ruscoder** [comment]
Now we are working on workaround for this issue

**Comment by ruscoder** [comment]
There is an example how to get a workaround:
https://github.com/beda-software/drf-writable-nested#validation-problem-for-nested-serializers-with-unique-fields-on-update

**Comment by dz0** [comment]
but DRF also proposes  way to deal with bulk updates by explicitly including id field (as not read_only)
http://www.django-rest-framework.org/api-guide/serializers/#customizing-multiple-update

this way, one get instance from id

ps.: in my case I had custom kind of uniqueness validation (checked if objects not overlap), so I excluded current instance by id in my validation query.

**Comment by pmontu** [comment]
Would UniqueFieldsMixin move validations of unique_together as well?
