### ISSUE TITLE
Add support for custom primary key field

### ISSUE THREAD

**Issue by ruscoder** [beda-software/drf-writable-nested#10]
We have some issues (#9 #3) which caused by using `id` instead of `pk`.

Also, there is no way to use a custom primary key field.

**Comment by tjwalch** [comment]
I pushed a commit that should fix this to my fork (and pull request).

**Comment by ruscoder** [comment]
@tjwalch Great work! I'll see your PR soon

**Comment by ruscoder** [comment]
@tjwalch Thanks, I've merged it into master.
