### ISSUE TITLE
Drop Python 2.7

### ISSUE THREAD

**Issue by johnthagen** [beda-software/drf-writable-nested#109]
Django and DRF have both dropped Python 2.7. `drf-writable-nested` should consider following suit.

Currently, we must use `pytest` at `<5` in `requirements.txt` to support Python 2.7.

**Comment by ruscoder** [comment]
@johnthagen  I agree with dropping python2.7 compatibility.

**Comment by johnthagen** [comment]
@ruscoder Would like me to go ahead and roll that into #108? It would drop a lot of builds from the matrix since we had to add some more to support new Python and Django versions.

**Comment by ruscoder** [comment]
@johnthagen Yes, it will be great!

**Comment by johnthagen** [comment]
> @johnthagen Yes, it will be great!

@ruscoder Done.
