### ISSUE TITLE
How to do a PUT request with nested object?

### ISSUE THREAD

**Issue by danilke** [beda-software/drf-writable-nested#11]
Hi, for example I have object Addreess: 
`` '{
    "zip": 122200,
    "country": {
        "id": 1,
        "title": "Italy"
    }  
}'``

And I want to change address country to existing object France:
``"country": {
        "id": 2,
        "title": "France"
    }  ``

w can I do PUT request to object without creating new column in DB? Thank you.

**Comment by danilke** [comment]
OK, I find solution: rewrite `id` -> `pk`. But why isn't possible to do it with ID? Thanks.

**Comment by ruscoder** [comment]
@danilke 
Hello!
This feature has been already implemented but not merged yet. (#10)

**Comment by ruscoder** [comment]
@danilke Now you can pass `id` field instead of `pk` using version 0.2.0

**Comment by danilke** [comment]
Thank you!
