### ISSUE TITLE
Not compatible with Django 3.1

### ISSUE THREAD

**Issue by KrYpTeD974** [beda-software/drf-writable-nested#115]
The file mixins.py imports FieldDoesNotExist which has been moved to another package.
from django.core.exceptions.

`from django.core.exceptions import FieldDoesNotExist`  should be used instead of 
`from django.db.models import ProtectedError, FieldDoesNotExist`

**Comment by ruscoder** [comment]
Fixed by #114. The fix is available in 0.6.1 in PyPI
