### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by aabanaag** [beda-software/drf-writable-nested#120]
I followed the instructions, installed `pip install drf-writable-nested` but I can't see any clear instructions on how to properly use WritableNestedSerializer.

![image](https://user-images.githubusercontent.com/2245822/94462556-4962fb80-01ee-11eb-80fe-cfe4ec85ad1b.png)

Here is a portion of my requirements.txt

````
Django==3.1.1
django-cors-headers==3.5.0
django-environ==0.4.5
django-filter==2.3.0
django-health-check==3.14.1
django-redis==4.12.1
djangorestframework==3.11.1
drf-extensions==0.6.0
drf-writable-nested==0.6.1
````

**Comment by ruscoder** [comment]
Hello @aabanaag! Make sure that your project and IDE use the right environment with installed requirements.

**Comment by aabanaag** [comment]
Sorry I'm confused, my setup IDE is Pycharm and configured my python interpreter as remote docker-compose config.
