### ISSUE TITLE
UniqueFieldMixin does not work for djangorestframwork of versions >= 3.11

### ISSUE THREAD

**Issue by iyinolu** [beda-software/drf-writable-nested#150]

**Comment by ir4y** [comment]
Hi,

Thank you for contributing.

`UniqueFieldsMixin` is fully covered with unti tests for djangorestframwork >= 3.11
https://app.codecov.io/gh/beda-software/drf-writable-nested/blob/a3d53dc15de3f052313851f399db36a73f9e5778/drf_writable_nested/mixins.py

If you still experiencing this issue, could you please create a pull request with a test?

Best,
Ilya
