### ISSUE TITLE
Migrate to new CI platform

### ISSUE THREAD

**Issue by johnthagen** [beda-software/drf-writable-nested#161]
If you navigate here: https://www.travis-ci.com/beda-software/drf-writable-nested

> 404

This project will need to migrate to either GitHub Actions or Circle CI. GitHub Actions seems to be the most popular currently.

[Travis CI (.com) is no longer free for FOSS projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)

**Comment by ir4y** [comment]
It is done https://github.com/beda-software/drf-writable-nested/commit/a8f185e2acb79d409b650b4b391b862e493fc927
