### ISSUE TITLE
Can this package be made to not depend on contenttypes?

### ISSUE THREAD

**Issue by infintesimal** [beda-software/drf-writable-nested#37]
I saw this package and was excited for the ease of using writable nested serializers. But then I realized it doesn't work in my app because I don't run django.contrib.contenttypes (nor do I want to for many reasons).

This is an open ended ask, I am happy to help if it can be done and if it would merit the effort.

**Comment by ruscoder** [comment]
Hello @infintesimal!
We use contenttypes to support generic reverse relation. Django always has contenttypes in contrib, so you don't need to install an additional package. Simply don't use generic relations in your models.
