### ISSUE TITLE
Removing nested objects from validated_data during create

### ISSUE THREAD

**Issue by stuartaccent** [beda-software/drf-writable-nested#39]
I know this is an odd thing to do, I just want to see if its considered a bug.

Consider the following:

```
class ChildSerializer(serializers.ModelSerializer):
    class Meta:
        model = Child
        fields = ('id', 'name')

class ParentSerializer(WritableNestedModelSerializer):
    children = ChildSerializer(many=True)

    class Meta:
        model = Parent
        fields = ('id', 'name', 'children')

    def create(self, validated_data):
        del validated_data['children'][0]
        return super().create(validated_data)

# TEST
class RemovingValidatedDataTests(TestCase):

    def test_should_not_save_deleted(self):
        data = {
            'name': 'Fred Smith',
            'children': [
                {'name': 'Bobby'},
                {'name': 'Steve'}
            ]
        }
        serializer = ParentSerializer(data=data)
        self.assertTrue(serializer.is_valid())
        serializer.save()

        self.assertEqual(Parent.objects.count(), 1)
        self.assertEqual(Child.objects.count(), 1) . # fails is still 2
```

Using the above the `Child.objects.count()` is still `2` due to the fact that the `ChildSerializer` has the `ParentSerializer.initial_data['children']` passed to it, and does not ever go near what was validated by the `ParentSerializer`.

Your thoughts would be appreciated. Thanks, Stu

**Comment by ruscoder** [comment]
Hello @stuartaccent! 

This behavior is correct. We use `initial_data` instead of `validated_data` because we run the validation process on each children serializer with initial data (otherwise validated data might be changed, like in your example). So, I don't consider this as a bug.

**Comment by stuartaccent** [comment]
Hi @ruscoder 

Thanks for the clarification.
