### ISSUE TITLE
DRFs built-in API not working, sending POST from elsewhere does

### ISSUE THREAD

**Issue by julianflapper** [beda-software/drf-writable-nested#40]
Hi,

Just started experimenting with drf-writable-nested and I couldn't get it to work. Very simple model, almost identical to your example in the README.md.
(User and Profile, profile has OneToOne with User) 

I couldn't just get it to work with DRFs built-in API interface. It kept setting the profile to NULL and it was extremely frustrating. Until I found another issue here that had was also fixed by using a different client to interact with the API. So I tried that, and it worked.

The first one is the entry from the DRF API interface, and the second is from another REST client.
```
[
    {
        "pk": 1,
        "email": "john@doe.com",
        "date_joined": "2018-05-01",
        "profile": null
    },
    {
        "pk": 2,
        "email": "jake@doe.com",
        "date_joined": "2018-05-01",
        "profile": {
            "pk": 1,
            "first_name": "Jake",
            "last_name": "Doe"
        }
    }
]
```

I do like DRFs built-in client, however. 
Is there anything that may cause this issue, and is there any way to solve it?

EDIT:
Versions
Python 3.6
Django 2.0.4
DRF 3.8.2
drf-writable-nested 0.4.2

EDIT2:
More specifically, it seems to make the profile field NULL when sent form the HTML form window in DRF, while it does work normally when sent from the Raw data tab.

**Comment by projkov** [comment]
@julianflapper Hello.
I used standard models from repo and I have default Django rest framework form.
![2018-06-13 16 39 15](https://user-images.githubusercontent.com/4172228/41343473-eea937c2-6f28-11e8-8383-9b94d2a18161.png)
As I see, "Lists are not currently supported in HTML input" so we can't get correct form view and usage in HTML form tab.
So you can use Raw data tab for debug purposes.

**Comment by julianflapper** [comment]
Yeah though it does show the HTML form. It doesn't show the "Lists are not currently supported" for me. Anyways, using raw data is fine to me. Just thought I had an issue in my code or something was wrong with yours, but turns out it's neither :) Thanks
