### ISSUE TITLE
many to many use through error: Cannot use add() on a ManyToManyField which specifies an intermediary model. Use backbay.Content_Tags's Manager instead.

### ISSUE THREAD

**Issue by iyuhang** [beda-software/drf-writable-nested#56]
many to many use through error: Cannot use add() on a ManyToManyField which specifies an intermediary model. Use backbay.Content_Tags's Manager instead.

**Comment by ruscoder** [comment]
Hello @iyuhang! 

This package doesn't support m2m relations with an intermediate model. You should manually handle these relations.

**Comment by shepherd1530** [comment]
Hi @ruscoder is there an update to this feature?
