### ISSUE TITLE
Avoid update to other instances

### ISSUE THREAD

**Issue by rbusquet** [beda-software/drf-writable-nested#73]
I need help on an issue I'm having and I don't see a standalone solution for this inside this project without overriding the parent serializer.

I have serializers setup like this:

```python
class ChildSerializer(serializers.ModelSerializer):
    class Meta:
        model = Child
        fields = ('pk', 'name')


class ParentSerializer(WritableNestedModelSerializer):
    child = ChildSerializer()

    class Meta:
        model = Parent
        fields = ('pk', 'name', 'child')
```

I have two instances of each model set up like this;

```python
>>> Parent.objects.values()
<QuerySet [{'id': 1, 'name': 'parent 1', 'child_id': 1}, {'id': 2, 'name': 'parent 2', 'child_id': 2}]>
>>> Child.objects.values()
<QuerySet [{'id': 1, 'name': 'child 1'}, {'id': 2, 'name': 'child 2'}]>
```

If I setup my POST or PATCH request like this:

```json
POST /api/parent/1
{
    "name": "Changing parent 1", 
    "child": {
        "pk": 2, 
        "name": "Changing name of child 2"
    }
}
```
I end-up altering the child with id 2 and setting this value on parent 1.

```python
>>> Parent.objects.values()
<QuerySet [{'id': 1, 'name': 'Changing parent 1', 'child_id': 2}, {'id': 2, 'name': 'parent 2', 'child_id': 2}]>
>>> Child.objects.values()
<QuerySet [{'id': 1, 'name': 'child 1'}, {'id': 2, 'name': 'Changing name of child 2'}]>
```

Is there a way to avoid this? Now I have to override `validate_child` on the parent serializer and check `initial_data` to see if the pk is different.

**Comment by ruscoder** [comment]
Hello @rbusquet!

It is OK, that the child model was altered. If you want to create a new child, you need to reset pk of the child serializer.

Try something like this:
```
POST /api/parent/1
{
    "name": "Changing parent 1", 
    "child": {
        "name": "Changing name of child 2"
    }
}
```

**Comment by rbusquet** [comment]
Is there a way to explicitly block the update of an FK to another instance that already exists?

The issue here is that I want to enforce the persistence of the FK on the `Parent` object. I want to block on the serializer level the ability of the change `parent.child_id` from 1 to 2, keeping the ability of updating.

**Comment by ruscoder** [comment]
@rbusquet Have you tried to add validation to the parent serializer to check that child_id wasn't changed?

**Comment by rbusquet** [comment]
As mentioned in the issue, I ended up adding the validation to the serializer.

I'm just concerned as this can be an issue that's not really highlighted on the documentation. The current value for the FK is not considered anytime when retrieving/updating the nested serializers. Looks like this is by design and the correct fix is to implement the validation on the parent serializer.

Thanks for the responses.

**Comment by stygmate** [comment]
+1 for adding this in documentation.
I ended with that problem (revealed by a pentest) !

**Comment by stygmate** [comment]
@rbusquet can you share your validation code ?
