### ISSUE TITLE
Validation problem for nested serializers with unique fields on update

### ISSUE THREAD

**Issue by ubuhuo** [beda-software/drf-writable-nested#80]
I'm sorry to ask this question again, but I tried many times and it still had problems.

```
Basics:
Django-2.1.4
DRF-3.9.2
drf-writable-nested-0.5.1
```

```python
# model.py
from django.db import models


class Child(models.Model):
    field = models.CharField(unique=True, max_length=100)
    field_two = models.CharField(max_length=100)
    field_three = models.CharField(max_length=100)


class Parent(models.Model):
    child = models.ForeignKey('Child', on_delete=models.CASCADE)
```

```python
# serializers.py
from rest_framework import serializers
from drf_writable_nested import UniqueFieldsMixin, NestedUpdateMixin, NestedCreateMixin
from .models import Child, Parent


class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
    class Meta:
        model = Child
        fields = '__all__'


class ParentSerializer(NestedCreateMixin, NestedUpdateMixin, serializers.ModelSerializer):
    child = ChildSerializer()

    class Meta:
        model = Parent
        fields = '__all__'
```

```python
# views.py
from rest_framework.viewsets import ModelViewSet

from .models import Parent
from .serializers import ParentSerializer


class TestViewSet(ModelViewSet):
    queryset = Parent.objects.all()
    serializer_class = ParentSerializer
```

```python
# url.py
...

from practice.views import TestViewSet

router = DefaultRouter(trailing_slash=False)
router.register(r'test', TestViewSet, base_name='test')

...
```

```
# POST

url: http://127.0.0.1:8000/test
data: {
    "child": {
        "field": "asd",
        "field_two": "asdasd",
        "field_three": "asdasdasd"
    }
}

# return json
{
    "id": 1,
    "child": {
        "id": 1,
        "field": "asd",
        "field_two": "asdasd",
        "field_three": "asdasdasd"
    }
}

# PUT
url: http://127.0.0.1:8000/test/1
data: {
    "child": {
        "field": "asd",
        "field_two": "asdasd",
        "field_three": "asdasdasdaaaaaaaaaa"
    }
}

# return json
{
    "child": {
        "field": [
            "This field must be unique."
        ]
    }
}
```

I've tried most of the methods that I can Google.

But none of them can solve my problem well.

I was really happy when I found this plug-in.

But it didn't work after I tried.

I read about the source code, but I couldn't understand the function of the code.

I'm a novice. If I make some low-level mistakes, I hope you can tell me.

**Comment by ubuhuo** [comment]
@ruscoder

**Comment by ubuhuo** [comment]
supplement:

Python-3.7.2

**Comment by mumumumu** [comment]
Have you already tried removing the uniqueness validator from the child serializer? Something like:
```
class ChildSerializer(serializers.ModelSerializer):
    class Meta:
        model = Child
        fields = '__all__'
        extra_kwargs = {
            'field': {
                'validators': [],
            }
        }
```

Source: https://medium.com/django-rest-framework/dealing-with-unique-constraints-in-nested-serializers-dade33b831d9

**Comment by ubuhuo** [comment]
I just tried it.
It doesn't work within this framework.
@mumumumu

**Comment by ruscoder** [comment]
Hello! You have to send Id of child in the put request data. 

Try the next data for the put request:
```
child: { id: 1, ... }
```

As it was returned by the post request.

**Comment by ubuhuo** [comment]
Amazing!

But why do I have to do this?

I've seen the source code, it doesn't need to enter the pk of table.

Does this mean that I have to enter the PK of the child table in every PUT request?

If you have time, could explain to me what the source code did, please.

I saw your comments in the source code, you say: Moves `UniqueValidator`'s from the validation stage to the save stage.

But I can only see that you define `_validate_unique_fields` method and then call it in the `create` function.

Shouldn't uniqude validation be performed before the `create` method call ?

If you have time, I really hope you can help me understand the meaning of the source code better.

I am from China. My English is not very good. All the dialogues are translated through Baidu. There may be some problems in language expression. I hope you don't mind.
