### ISSUE TITLE
Query regarding auto creation of related field with foreign key.

### ISSUE THREAD

**Issue by Niranjan-Rathod** [beda-software/drf-writable-nested#82]
What happens when the field having a foreign key relationship is not nested in itself?
For example in the example given in README, if the data for access_key is like following

    data = {
	    'username': 'test',
	    'profile': {
	        'key': 'key',
	        'sites': [
	            {
	                'url': 'http://google.com',
	            },
	            {
	                'url': 'http://yahoo.com',
	            },
	        ],
	        'avatars': [
	            {
	                'image': 'image-1.png',
	            },
	            {
	                'image': 'image-2.png',
	            },
	        ],
	    },
	}

I have modified the field in ProfileSerializer to 

    # Direct FK relation
    access_key = models.CharField(max_length=100)

But it doesn't seem to work. Any suggestions?

**Comment by ruscoder** [comment]
Hello, @aaryanUV. 
In your example, you are posting `key` but in the model Profile you only have `access_key`.  
Could you please create a PR with a broken test example or show all source code with models/serializers and example query.
