### ISSUE TITLE
Fix CI build for Django 2.2

### ISSUE THREAD

**Issue by ruscoder** [beda-software/drf-writable-nested#87]
It seems that everything is OK with tests for 2.2 but the build fails on the CI.

Django 2.2 was temporarily removed from travis/tox https://github.com/beda-software/drf-writable-nested/commit/f06df1a2dcac222f519bb368da273150036b8323
Failing build:
https://travis-ci.org/beda-software/drf-writable-nested/jobs/547545561

**Comment by auvipy** [comment]
I will give it a try.

**Comment by ruscoder** [comment]
@auvipy OK, any updates on this?

**Comment by auvipy** [comment]
not yet
