### ISSUE TITLE
Update doesn't really update

### ISSUE THREAD

**Issue by chezwhite** [beda-software/drf-writable-nested#9]
Hi, I installed drf-writable-nested serializers on my Django REST API and I've seen that it doesn't really update the Reverse FK relations. I have these models:
```
class Question(models.Model):
    title = models.CharField(max_length=500)
    last_modified = models.DateField(auto_now=True)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, related_name='questions')

    def __str__(self):
        return self.title

    class Meta:
        unique_together = (("id", "chapter"),)
        ordering = ['id']

class Answer(models.Model):
    title = models.CharField(max_length=1000)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')

    def __str__(self):
        return self.title

    class Meta:
        unique_together = (("id", "question"),)
        ordering = ['id']
```
And these are my serializers:
```
class AnswerDetailSerializer(serializers.ModelSerializer):
    class Meta:
        model = Answer
        fields = ('id', 'title', 'correct')

class QuestionDetailSerializer(WritableNestedModelSerializer):
    answers = AnswerDetailSerializer(many=True)
    class Meta:
        model = Question
        fields = ('__all__')

```
So when I update a question with nested answers it just deletes all answers and create new ones, which gives me problems since I am also using the model Answers in another ManyToMany relation saving answers in Tests.

Is it because I use it wrong or it is just not updating but just delete and create? In that case I will have to write my own writable nested serializer.

**Comment by ruscoder** [comment]
Hello @chezwhite 
This package have a limitation: you have to use `pk` field to determine which instances should be updated.

As I see, you use `id` instead of `pk` in serializers and data which you sent. There was a task with the same problem #3.

In near future, I'll try to fix this behavior.

**Comment by chezwhite** [comment]
oh ok I see the closed issue now. Sorry I don't know why I just though it should be only in open issues.

Thanks for the quick reply.
